config/routes.rb
Rails.application.routes.draw do
  resources :routes
  resources :blocks

  namespace :admin do
    resources :users
    resources :centers do
      delete :thumbnail, on: :member, action: :destroy_thumbnail
    end
    resources :subscriptions
    resources :courses
    resources :coworkings
    resources :loisirs
    resources :order_subscriptions
    resources :order_courses
    resources :relaxations
    resources :restaurations

    root to: 'users#index'
  end
  get 'coworkings/index'
  root 'home_page#index'
  resources :centers
  resources :subscriptions
  devise_for :users
  resources :users
  resources :order_courses

  scope '/courses' do
    get '/', to: redirect("/courses/1"), as: 'courses'
    get ":center_id", to: 'courses#index', as: 'courses_from_center'
  end

  scope '/order_courses' do
    post 'book_course', to: 'order_courses#book_course', as: 'order_course_book_course'
    post 'refund_course', to: 'order_courses#refund_course', as: 'order_course_refund_course'
  end

  scope '/order_subscriptions' do
    post 'book_subscription', to: 'order_subscriptions#book_subscription', as: 'order_subscription_book_subscription'
  end

  resources :order_subscriptions
  resources :restaurations
  resources :coworkings
  resources :relaxations
  resources :loisirs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  scope '/checkout' do
    get 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'refund', to: 'checkout#refund', as: 'checkout_refund'
  end

  scope '/checkout_subscription' do
    get 'create', to: 'checkout_subscription#create', as: 'checkout_subscription_create'
    get 'cancel', to: 'checkout_subscription#cancel', as: 'checkout_subscription_cancel'
    get 'success', to: 'checkout_subscription#success', as: 'checkout_subscription_success'
  end
end

app/models/block.rb
class Block < ApplicationRecord
end

app/models/center.rb
class Center < ApplicationRecord
  has_many :courses
  has_many :users
  has_many :restaurants
  has_many :coworkings
  has_many :relaxations
  has_many :loisirs
  has_one_attached :thumbnail
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :center
  has_many :order_courses
  validates :name, presence: true
  validates :price, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :max_attendees, presence: true
  validates :week_day, presence: true



  def week_day_to_s
    return Date::DAYNAMES[(week_day + 1) % 7]
  end

end

app/models/course_event.rb
class CourseEvent
  attr_accessor :monday_date, :course

  def initialize(course, monday_date)
    @course = course
    @monday_date = monday_date
  end

  def date
    return @monday_date + @course.week_day
  end

  def start_time
    event_date = date.to_datetime
    return event_date.change({ hour: @course.start_time.hour, min: @course.start_time.min })
  end

  def end_time
    event_date = date.to_datetime
    return event_date.change({ hour: @course.end_time.hour, min: @course.end_time.min })
  end

  def reserved_slots
    return course.order_courses.where(date: date).count
  end

  def available_slots
    return course.max_attendees - reserved_slots
  end

  def has_available_slots
    return available_slots > 0
  end

  # Check if user_id has reservation for the course
  def has_slots_reserved(user_id)
    !user_reserved_slot(user_id).nil?
  end

  def user_reserved_slot(user_id)
    @course.order_courses.where(date: date, user_id: user_id)[0]
  end

  def is_past
    start_time < Time.now
  end
end

app/models/coworking.rb
class Coworking < ApplicationRecord
  belongs_to :center
end

app/models/loisir.rb
class Loisir < ApplicationRecord
  belongs_to :center
end

app/models/order_course.rb
class OrderCourse < ApplicationRecord
  belongs_to :course
  belongs_to :user

  def start_date_time
    new_time = date.to_datetime
    new_time = new_time.change({ hour: course.start_time.hour, min: course.start_time.min })
    return new_time
  end

  def is_future
    return start_date_time > Time.now
  end
end

app/models/relaxation.rb
class Relaxation < ApplicationRecord
  belongs_to :center
end

app/models/restauration.rb
class Restauration < ApplicationRecord
  belongs_to :center
end

app/models/route.rb
class Route < ApplicationRecord
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  has_many :order_subscriptions
  validates :name, presence: true
  validates :price, presence: true
  validates :description, presence: true
  validates :duration, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :order_courses
  has_many :courses, through: :order_courses
  has_many :order_subscriptions
  has_many :subscriptions, through: :order_subscriptions
  belongs_to :center
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  def current_subscription
    order_subscriptions.find { |order| order.end_date > Date.today }
  end

  def has_active_subscription
    !current_subscription.nil?
  end

  def has_course
    order_courses.count < 1
  end

  def future_courses
    order_courses.filter { |order_course| order_course.is_future }
  end
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def index
    @center = Center.all + Center.all
  end
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/centers_helper.rb
module CentersHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/loisirs_helper.rb
module LoisirsHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home_page/index.html.erb
    <!--bannière-->
<section class="jumbotron jumbotron-fluid text-center">
  <div class="container-banner ">
    <%= image_tag("bann.jpg", class: "banpic w-100")%>
  </div>
</section>
<div>
  <h3 class=" text-center m-5 ">Nos services</h3>
</div>
<!--Card de nos services-->
<div class="album ">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="card mb-4 box-shadow bg-dark text-white">
          <%= image_tag("climb2.jpg", class: "card-img-top") %>
          <div class="card-img-overlay">
            <h2 class="card-text d-flex justify-content-start "> BLOCS</h2>
            <h4 class="card-text-cache d-flex justify-content-center align-items-center"><%= link_to "Decouverte des blocs", blocks_path %> </h4>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card mb-4 box-shadow bg-dark text-white">
          <%= image_tag("climb3.png", class: "card-img-top") %>
          <div class="card-img-overlay">
            <h2 class="card-text d-flex justify-content-start "> VOIES</h2>
            <h4 class="card-text-cache d-flex justify-content-center"><%= link_to "Decouverte des voies", routes_path %> </h4>
          </div>
        </div>
      </div>
      <div class="col-md-4 ">
        <div class="card mb-4 box-shadow bg-dark text-white ">
          <%= image_tag("hamburger.jpg", class: "card-img-top ") %>
          <div class="card-img-overlay">
            <h2 class="card-text d-flex justify-content-start "> RESTAURATION</h2>
            <% if !user_signed_in? %>
              <h4 class="card-text-cache d-flex justify-content-center"><%= link_to "Une petite faim?", restaurations_path %> </h4>
            <% else %>
              <h4 class="card-text-cache d-flex justify-content-center"><%= link_to "Une petite faim dans votre salle ?", restauration_path(current_user.center.id) %> </h4>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card mb-4 box-shadow bg-dark text-white">
          <%= image_tag("spa.jpg", class: "card-img-top") %>
          <div class="card-img-overlay">
            <h2 class="card-text d-flex justify-content-start "> DETENTE</h2>
            <% if !user_signed_in? %>
            <h4 class="card-text-cache d-flex justify-content-center"><%= link_to "Espace détente", relaxations_path %></h4>
            <% else %>
            <h4 class="card-text-cache d-flex justify-content-center"><%= link_to "Espace détente dans votre salle", relaxation_path(current_user.center.id) %></h4>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card mb-4 box-shadow bg-dark text-white">
          <%= image_tag("cow.jpg", class: "card-img-top") %>
          <div class="card-img-overlay">
            <h2 class="card-text d-flex justify-content-start "> COWORKING</h2>
            <% if !user_signed_in? %>
            <h4 class="card-text-cache d-flex justify-content-center"> <%= link_to " Espace coworking", coworkings_path %></h4>
            <% else %>
            <h4 class="card-text-cache d-flex justify-content-center"> <%= link_to " Espace coworking dans votre salle", coworking_path(current_user.center.id) %></h4>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card mb-4 box-shadow bg-dark text-white">
          <%= image_tag("loisirs.jpg", class: "card-img-top") %>
          <div class="card-img-overlay">
            <h2 class="card-text d-flex justify-content-start "> LOISIRS</h2>
            <% if !user_signed_in? %>
            <h4 class="card-text-cache d-flex justify-content-center"> <%= link_to "Espace loisirs", loisirs_path %></h4>
            <% else %>
            <h4 class="card-text-cache d-flex justify-content-center"> <%= link_to "Espace loisirs dans votre salle", loisir_path(current_user.center.id) %></h4>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div>
  <h3 class=" text-center m-5 ">Nos salles</h3>
</div>
<div>
<div class="swiper-container">
  <div class="swiper mySwiper">
    <div class="swiper-wrapper d-flex align-items-start text-center">
      <% @center.each do |center| %>
        <div class="swiper-slide mr-2">
          <p><%= center.name %></p>
          <% if center.thumbnail.attached?%>
            <%= image_tag center.thumbnail, class: "img-carousel" %>
          <% else %>
            <%= image_tag("climb1.jpg", class: "img-carousel") %>
          <% end %>
          <%= button_to "Voir la salle", center_path(center.id), class: "btn btn-info btn-index-page ", method: "get" %>
        </div>
      <% end %>
    </div>
      <div class="swiper-button-next"></div>
      <div class="swiper-button-prev"></div>
     
  </div>
   <div class="swiper-pagination"></div>
  </div>
  </div>
  <%= javascript_include_tag('homepage.js') %>