config/routes.rb
Rails.application.routes.draw do
  resources :routes
  resources :blocks

  namespace :admin do
    resources :users
    resources :centers do
      delete :thumbnail, on: :member, action: :destroy_thumbnail
    end
    resources :subscriptions
    resources :courses
    resources :coworkings
    resources :loisirs
    resources :order_subscriptions
    resources :order_courses
    resources :relaxations
    resources :restaurations

    root to: 'users#index'
  end
  get 'coworkings/index'
  root 'home_page#index'
  resources :centers
  resources :subscriptions
  devise_for :users
  resources :users
  resources :order_courses

  scope '/courses' do
    get '/', to: redirect("/courses/1"), as: 'courses'
    get ":center_id", to: 'courses#index', as: 'courses_from_center'
  end

  scope '/order_courses' do
    post 'book_course', to: 'order_courses#book_course', as: 'order_course_book_course'
    post 'refund_course', to: 'order_courses#refund_course', as: 'order_course_refund_course'
  end

  scope '/order_subscriptions' do
    post 'book_subscription', to: 'order_subscriptions#book_subscription', as: 'order_subscription_book_subscription'
  end

  resources :order_subscriptions
  resources :restaurations
  resources :coworkings
  resources :relaxations
  resources :loisirs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  scope '/checkout' do
    get 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'refund', to: 'checkout#refund', as: 'checkout_refund'
  end

  scope '/checkout_subscription' do
    get 'create', to: 'checkout_subscription#create', as: 'checkout_subscription_create'
    get 'cancel', to: 'checkout_subscription#cancel', as: 'checkout_subscription_cancel'
    get 'success', to: 'checkout_subscription#success', as: 'checkout_subscription_success'
  end
end

app/models/block.rb
class Block < ApplicationRecord
end

app/models/center.rb
class Center < ApplicationRecord
  has_many :courses
  has_many :users
  has_many :restaurants
  has_many :coworkings
  has_many :relaxations
  has_many :loisirs
  has_one_attached :thumbnail
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :center
  has_many :order_courses
  validates :name, presence: true
  validates :price, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :max_attendees, presence: true
  validates :week_day, presence: true



  def week_day_to_s
    return Date::DAYNAMES[(week_day + 1) % 7]
  end

end

app/models/course_event.rb
class CourseEvent
  attr_accessor :monday_date, :course

  def initialize(course, monday_date)
    @course = course
    @monday_date = monday_date
  end

  def date
    return @monday_date + @course.week_day
  end

  def start_time
    event_date = date.to_datetime
    return event_date.change({ hour: @course.start_time.hour, min: @course.start_time.min })
  end

  def end_time
    event_date = date.to_datetime
    return event_date.change({ hour: @course.end_time.hour, min: @course.end_time.min })
  end

  def reserved_slots
    return course.order_courses.where(date: date).count
  end

  def available_slots
    return course.max_attendees - reserved_slots
  end

  def has_available_slots
    return available_slots > 0
  end

  # Check if user_id has reservation for the course
  def has_slots_reserved(user_id)
    !user_reserved_slot(user_id).nil?
  end

  def user_reserved_slot(user_id)
    @course.order_courses.where(date: date, user_id: user_id)[0]
  end

  def is_past
    start_time < Time.now
  end
end

app/models/coworking.rb
class Coworking < ApplicationRecord
  belongs_to :center
end

app/models/loisir.rb
class Loisir < ApplicationRecord
  belongs_to :center
end

app/models/order_course.rb
class OrderCourse < ApplicationRecord
  belongs_to :course
  belongs_to :user

  def start_date_time
    new_time = date.to_datetime
    new_time = new_time.change({ hour: course.start_time.hour, min: course.start_time.min })
    return new_time
  end

  def is_future
    return start_date_time > Time.now
  end
end

app/models/relaxation.rb
class Relaxation < ApplicationRecord
  belongs_to :center
end

app/models/restauration.rb
class Restauration < ApplicationRecord
  belongs_to :center
end

app/models/route.rb
class Route < ApplicationRecord
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  has_many :order_subscriptions
  validates :name, presence: true
  validates :price, presence: true
  validates :description, presence: true
  validates :duration, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :order_courses
  has_many :courses, through: :order_courses
  has_many :order_subscriptions
  has_many :subscriptions, through: :order_subscriptions
  belongs_to :center
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  def current_subscription
    order_subscriptions.find { |order| order.end_date > Date.today }
  end

  def has_active_subscription
    !current_subscription.nil?
  end

  def has_course
    order_courses.count < 1
  end

  def future_courses
    order_courses.filter { |order_course| order_course.is_future }
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(current_user.id)
  end

end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/centers_helper.rb
module CentersHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/coworkings_helper.rb
module CoworkingsHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/loisirs_helper.rb
module LoisirsHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<%# ============================ User Information ===================================== %>
<div class="container">
  <div class="card m-3">
    <div class="card-header text-center">
      <h3 class="m-0"> Mon compte </h3>
    </div>
  </div>
  <div class="card m-3">
    <div class="card-header">
      <span class="d-flex justify-content">
        <i class="d-flex align-items-center fas fa-regular fa-circle-info mx-3"></i>
        <h5 class="m-0"> Mes informations </h5>
      </span>
    </div>
    <div class="card-body d-flex justify-content-around align-items-center">
      <div>
        <% if !@user.first_name.nil? %>
          <p class="card-title"> <b>Prénom : </b><%= @user.first_name %></p>
        <% end %>
        <% if !@user.last_name.nil? %>
          <p class="card-title"> <b>Nom de famille : </b><%= @user.last_name%></p>
        <% end %>
        <% if !@user.birth_date.nil? %>
          <p class="card-title"> <b>Date de naissance : </b><%= @user.birth_date.strftime("%d/%m/%Y") %></p>
        <% end %>
        <p class="card-title"> <b>Email : </b><%= @user.email%></p>
        <%= button_to 'Modifier mes informations', edit_user_registration_path(@user), method: :get, class: "btn btn-success" %>
      </div>
      <div class="text-center">
        <% if @user.has_active_subscription %>
          <p><strong> Votre abonnement expire le </strong><br />
            <%= @user.current_subscription.end_date.strftime("%d/%m/%Y") %></p>
        <% else %>
        <% end %>
      </div>
    </div>
  </div>
  <%# ================================= Course ==================================%>
  <div class="card m-3">
    <div class="card-header">
      <span class="d-flex justify-content">
        <i class="d-flex align-items-center fa-solid fa-calendar-days mx-3"></i>
        <h5 class="m-0"> Historique des mes cours </h5>
      </span>
    </div>
    <div class="accordion" id="accordionPanelsStayOpenExample">
      <div class="accordion-item">
        <h2 class="accordion-header" id="panelsStayOpen-headingOne">
          <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne">
            Vos cours à venir
          </button>
        </h2>
        <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingOne">
          <div class="accordion-body d-flex flex-column align-items-center">
            <% if @user.has_course %>
              <h5 class="m-2">Vous n'avez pas de cours prévu</h5>
              <%= button_to "Réserver un cours", courses_path, method: :get, class: "btn btn-success" %>
            <% end %>
            <div class="row" >
              <% @user.future_courses.each do |order_course| %>
                <div class="col-sm-6">
                  <div class="card m-3" style="width: 18rem;">
                    <div class="card-header d-flex justify-content-center">
                      <h5> Commande n°<%= order_course.id %></h5>
                    </div>
                    <div class="d-flex flex-column m-2">
                      <p class="mb-0"> Intitulé du cours : <%= order_course.course.name %></p>
                      <p class="mb-0"> Date du cours : <%= order_course.start_date_time.strftime("%d/%m/%Y - %H:%M")%></p>
                      <p class="mb-0"> Prix : <%= order_course.course.price %> €</p>
                    </div>
                    <div class="m-2 d-flex justify-content-center">
                      <%= button_to "Annuler votre cours", order_course_refund_course_path(course_id: order_course.course.id, date: order_course.date, order_course_id: order_course.id, redirection_path: user_path), class: "btn btn-danger" %>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header" id="panelsStayOpen-headingTwo">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
            Toutes vos commandes
          </button>
        </h2>
        <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingTwo">
          <div class="accordion-body">
            <div class="row">
              <% @user.order_courses.each do |order_course| %>
                <div class="col-sm-6 d-flex justify-content-center">
                  <div class="card m-3" style="width: 18rem;">
                    <div class="card-header d-flex justify-content-center">
                      <h5> Commande n°<%= order_course.id %></h5>
                    </div>
                    <div class="d-flex flex-column m-2">
                      <p class="mb-0"> Intitulé du cours : <%= order_course.course.name %></p>
                      <p class="mb-0"> Date du cours : <%= order_course.date.strftime("%d/%m/%Y")%> - <%= order_course.course.start_time.strftime("%H:%M") %></p>
                      <p class="mb-0"> Prix : <%= order_course.course.price %> €</p>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%# ==================== Subscription ========================= %>
  <div class="card m-3">
    <div class="card-header">
      <span class="d-flex justify-content">
        <i class="d-flex align-items-center fa-solid fa-sheet-plastic mx-3"></i>
        <h5 class="m-0"> Mon abonnement </h5>
      </span>
    </div>
    <div class="accordion" id="accordionExample">
      <div class="accordion-item">
        <h2 class="accordion-header" id="headingOne">
          <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            Votre abonnement actif
          </button>
        </h2>
        <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
          <div class="accordion-body">
            <div class="d-flex align-items-center flex-column m-3">
              <% if !@user.has_active_subscription %>
                <h5 class="m-3 ">Vous n'avez pas encore d'abonnement</h5>
                <%= button_to "Prenez un abonnement", subscriptions_path, method: :get, class: "btn btn-success" %>
              <% else %>
                <div class="card m-3 row col-sm-6" style="width: 18rem;">
                  <div class="card-header d-flex justify-content-center">
                    <h5>Abonnement <%= @user.current_subscription.subscription.name %></h5>
                  </div>
                  <div class="d-flex flex-column m-2">
                    <p class="mb-0"> Date d'expiration : <%= @user.current_subscription.end_date.strftime("%d/%m/%Y") %></p>
                    <hr>
                    <p class="mb-0"><b>Prix : </b><%= @user.current_subscription.subscription.price %> €</p>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header" id="headingTwo">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
            Toutes vos commandes
          </button>
        </h2>
        <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
          <div class="accordion-body">
            <div class="row">
              <% @user.order_subscriptions.each do |order_subscription| %>
                <div class="col d-flex justify-content-center">
                  <div class="card m-3 row col-sm-6 " style="width: 18rem;">
                    <div class="card-header d-flex justify-content-center">
                      <h5> Commande n°<%= order_subscription.id %></h5>
                    </div>
                    <div class="d-flex flex-column m-2">
                      <p class="mb-0"> Nom de l'abonnement : <%= order_subscription.subscription.name %></p>
                      <p> Commandé le : <%= order_subscription.created_at.strftime("%d/%m/%Y") %></p>
                      <p class="mb-0"> Date d'expiration : <%= order_subscription.end_date.strftime("%d/%m/%Y") %></p>
                      <p class="mb-0"><b>Prix : </b><%= order_subscription.subscription.price %> €</p>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>