config/routes.rb
Rails.application.routes.draw do
  resources :routes
  resources :blocks

  namespace :admin do
    resources :users
    resources :centers do
      delete :thumbnail, on: :member, action: :destroy_thumbnail
    end
    resources :subscriptions
    resources :courses
    resources :coworkings
    resources :loisirs
    resources :order_subscriptions
    resources :order_courses
    resources :relaxations
    resources :restaurations

    root to: 'users#index'
  end
  get 'coworkings/index'
  root 'home_page#index'
  resources :centers
  resources :subscriptions
  devise_for :users
  resources :users
  resources :order_courses

  scope '/courses' do
    get '/', to: redirect("/courses/1"), as: 'courses'
    get ":center_id", to: 'courses#index', as: 'courses_from_center'
  end

  scope '/order_courses' do
    post 'book_course', to: 'order_courses#book_course', as: 'order_course_book_course'
    post 'refund_course', to: 'order_courses#refund_course', as: 'order_course_refund_course'
  end

  scope '/order_subscriptions' do
    post 'book_subscription', to: 'order_subscriptions#book_subscription', as: 'order_subscription_book_subscription'
  end

  resources :order_subscriptions
  resources :restaurations
  resources :coworkings
  resources :relaxations
  resources :loisirs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  scope '/checkout' do
    get 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'refund', to: 'checkout#refund', as: 'checkout_refund'
  end

  scope '/checkout_subscription' do
    get 'create', to: 'checkout_subscription#create', as: 'checkout_subscription_create'
    get 'cancel', to: 'checkout_subscription#cancel', as: 'checkout_subscription_cancel'
    get 'success', to: 'checkout_subscription#success', as: 'checkout_subscription_success'
  end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  has_many :order_subscriptions
  validates :name, presence: true
  validates :price, presence: true
  validates :description, presence: true
  validates :duration, presence: true
end

app/controllers/admin/subscriptions_controller.rb
module Admin
  class SubscriptionsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: %i[show edit update destroy]

  # GET /subscriptions or /subscriptions.json
  def index
    @subscriptions = Subscription.all

  end

  # GET /subscriptions/1 or /subscriptions/1.json
  def show
    @subscriptions = Subscription.find(params[:id])
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit; end

  # POST /subscriptions or /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to(subscription_url(@subscription), notice: 'Subscription was successfully created.') }
        format.json { render(:show, status: :created, location: @subscription) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
        format.json { render(json: @subscription.errors, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /subscriptions/1 or /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to(subscription_url(@subscription), notice: 'Subscription was successfully updated.') }
        format.json { render(:show, status: :ok, location: @subscription) }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
        format.json { render(json: @subscription.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /subscriptions/1 or /subscriptions/1.json
  def destroy
    @subscription.destroy

    respond_to do |format|
      format.html { redirect_to(subscriptions_url, notice: 'Subscription was successfully destroyed.') }
      format.json { head(:no_content) }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_subscription
    @subscription = Subscription.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def subscription_params
    params.require(:subscription).permit(:name, :price)
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= form_with(model: subscription) do |form| %>
  <% if subscription.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
        <% subscription.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/subscriptions/_subscription.html.erb
<div id="<%= dom_id subscription %>">
  <p>
    <strong>Name:</strong>
    <%= subscription.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= subscription.price %>
  </p>

</div>

app/views/subscriptions/edit.html.erb
<h1>Editing subscription</h1>
<%= render "form", subscription: @subscription %>
<br>
<div>
  <%= link_to "Show this subscription", @subscription %> |
  <%= link_to "Back to subscriptions", subscriptions_path %>
</div>

app/views/subscriptions/index.html.erb
<h2 class="display-6 text-center my-4">Abonnement Possible</h2>
<div class="d-flex justify-content-center  ">
  <div class=" container row row-cols-4 justify-content-center m-5 ">
    <% @subscriptions.each do |info|%>
      <div class="mh-25 col-12 col-sm-4 mb-4">
        <div class="card col  mt-1  ">
          <div class="card-header py-3">
            <h4 class="my-0 fw-normal text-center"><%=info.name%></h4>
          </div>
          <div class="card-body text-center">
            <h1 class="card-title pricing-card-title text-center"><%=info.price%>€<small class="text-muted fw-light"></small></h1>
            <ul class="list-unstyled mt-3 mb-4">
              <li><%=info.description%></li>
            </ul>
            <div class="d-flex justify-content-center">
              <% if !user_signed_in? or !current_user.has_active_subscription %>
                <%= button_to "S'abonner", order_subscription_book_subscription_path(subscription_id: info.id, duration: info.duration), method: :post, class:"btn btn-success"%>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end%>
  </div>
</div>

app/views/subscriptions/new.html.erb
<h1>New subscription</h1>
<%= render "form", subscription: @subscription %>
<br>
<div>
  <%= link_to "Back to subscriptions", subscriptions_path %>
</div>

app/views/subscriptions/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @subscription %>
<div>
  <%= link_to "Edit this subscription", edit_subscription_path(@subscription) %> |
  <%= link_to "Back to subscriptions", subscriptions_path %>
  <%= button_to "Destroy this subscription", @subscription, method: :delete %>
</div>