config/routes.rb
Rails.application.routes.draw do
  resources :routes
  resources :blocks

  namespace :admin do
    resources :users
    resources :centers do
      delete :thumbnail, on: :member, action: :destroy_thumbnail
    end
    resources :subscriptions
    resources :courses
    resources :coworkings
    resources :loisirs
    resources :order_subscriptions
    resources :order_courses
    resources :relaxations
    resources :restaurations

    root to: 'users#index'
  end
  get 'coworkings/index'
  root 'home_page#index'
  resources :centers
  resources :subscriptions
  devise_for :users
  resources :users
  resources :order_courses

  scope '/courses' do
    get '/', to: redirect("/courses/1"), as: 'courses'
    get ":center_id", to: 'courses#index', as: 'courses_from_center'
  end

  scope '/order_courses' do
    post 'book_course', to: 'order_courses#book_course', as: 'order_course_book_course'
    post 'refund_course', to: 'order_courses#refund_course', as: 'order_course_refund_course'
  end

  scope '/order_subscriptions' do
    post 'book_subscription', to: 'order_subscriptions#book_subscription', as: 'order_subscription_book_subscription'
  end

  resources :order_subscriptions
  resources :restaurations
  resources :coworkings
  resources :relaxations
  resources :loisirs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  scope '/checkout' do
    get 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'refund', to: 'checkout#refund', as: 'checkout_refund'
  end

  scope '/checkout_subscription' do
    get 'create', to: 'checkout_subscription#create', as: 'checkout_subscription_create'
    get 'cancel', to: 'checkout_subscription#cancel', as: 'checkout_subscription_cancel'
    get 'success', to: 'checkout_subscription#success', as: 'checkout_subscription_success'
  end
end

app/controllers/admin/courses_controller.rb
module Admin
  class CoursesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[show edit update destroy]

  # GET /courses or /courses.json
  def index
    # It's a variable that is used to determine the start date of the week.
    @center_id = params[:center_id]
    @center_id = 1 if @center_id.nil?
    monday_date = params.fetch(:start_date, Date.today).to_date.beginning_of_week(:monday)
    courses = Center.find(@center_id).courses
    @course_events = courses.map { |c| CourseEvent.new(c, monday_date) }
    @centers = Center.all
  end

  # GET /courses/1 or /courses/1.json
  def show
    @course = Course.find(params[:id])
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit; end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to(course_url(@course), notice: 'Course was successfully created.') }
        format.json { render(:show, status: :created, location: @course) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
        format.json { render(json: @course.errors, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to(course_url(@course), notice: 'Course was successfully updated.') }
        format.json { render(:show, status: :ok, location: @course) }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
        format.json { render(json: @course.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy

    respond_to do |format|
      format.html { redirect_to(courses_url, notice: 'Course was successfully destroyed.') }
      format.json { head(:no_content) }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_course
    @course = Course.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def course_params
    params.require(:course).permit(:name, :price, :start_time, :center_id, :max_attendees)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.erb
<div id="<%= dom_id course %>">
  <p>
    <strong>Name:</strong>
    <%= course.name %>
  </p>
  <p>
    <strong>Price:</strong>
    <%= course.price %>
  </p>
  <p>
    <strong>Horaire:</strong>
    <%= course.week_day_to_s %>: <%= course.start_time.to_s(:time) %> - <%= course.end_time.to_s(:time) %>
  </p>
  <p>
    <strong>Center:</strong>
    <%= course.center_id %>
  </p>
  <p>
    <strong>Nombre de places disponibles pour le 07/12/2022:</strong>
    <%= course.max_attendees %>
  </p>
</div>

app/views/courses/_form.html.erb
<%= form_with(model: course) do |form| %>
  <% if course.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>
      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>
  <div>
    <%= form.label :start_time, style: "display: block" %>
    <%= form.datetime_field :start_time %>
  </div>
  <div>
    <%= form.label :center_id, style: "display: block" %>
    <%= form.text_field :center_id %>
  </div>
  <div>
    <%= form.label :max_attendees, style: "display: block" %>
    <%= form.number_field :max_attendees %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>
<%= render "form", course: @course %>
<br>
<div>
  <%= link_to "Show this course", @course %> |
  <%= link_to "Back to courses", courses_path %>
</div>

app/views/courses/index.html.erb
<h3 class="mt-5 text-center">PLANNING DES COURS</h3>
<div class="d-flex justify-content-center">
  <%= select_tag "center", options_from_collection_for_select(Center.all, :id, :name, :selected => @center_id), :onchange => "goToCenterCourses(this.value)"%>
</div>
<div class="container d-flex justify-content-center">
  <%= week_calendar(events: @course_events, attribute: :start_time) do |date, course_events| %>
    <%= date.strftime("%d/%m/%Y") %>
    <% course_events.each do |course_event| %>
      <div class="  accordion course-event" id="accordion<%= course_event.course.id %>">
        <div class="accordion-item">
          <h2 class=" accordion-header" id="heading<%= course_event.course.id %>">
            <button class="accordion-button collapsed accordion-event-button <%= "reservation-success" if user_signed_in? && course_event.has_slots_reserved(current_user.id) %>" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<%= course_event.course.id %>" aria-expanded="false" aria-controls="collapse<%= course_event.course.id %>">
              <div class="m-2"><%= course_event.course.name %></div>
              <div class="m-2">(<%= course_event.start_time.strftime("%H:%M") %> - <%= course_event.end_time.strftime("%H:%M") %>)</div>
              <div class="m-2"><span class="badge bg-secondary <%= 'bg-danger' unless course_event.has_available_slots %>">Créneaux disponibles: <%= course_event.available_slots %>/<%= course_event.course.max_attendees %></span></div>
              <div class="m-2 text-decoration-underline">Prix: <%= course_event.course.price %>€</div>
            </button>
          </h2>
          <div id="collapse<%= course_event.course.id %>" class="accordion-collapse collapse" aria-labelledby="heading<%= course_event.course.id %>" data-bs-parent="#accordionExample">
            <div class="accordion-body">
              <% if course_event.is_past %>
                Le cours n'est plus disponible
              <% else %>
                <% if user_signed_in? && course_event.has_slots_reserved(current_user.id) %>
                  Vous avez déjà reservé ce créneau.
                  <%= button_to "Annuler votre cours", order_course_refund_course_path(course_id: course_event.course.id, date: course_event.date, order_course_id: course_event.user_reserved_slot(current_user.id), redirection_path: courses_path), class: "btn btn-danger" %>
                <% elsif course_event.has_available_slots %>
                  <%= button_to "Réserver", order_course_book_course_path(course_id: course_event.course.id, date: course_event.date), method: :post, class:"btn btn-success"%>
                <% else %>
                  Malheureusement il n'y a plus de créneaux disponibles.
                <% end%>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
<%= javascript_include_tag('courses.js') %>

app/views/courses/new.html.erb
<h1>New course</h1>
<%= render "form", course: @course %>
<br>
<div>
  <%= link_to "Back to courses", courses_path %>
</div>

app/views/courses/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @course %>
<div>
  <%= link_to "Edit this course", edit_course_path(@course) %> |
  <%= link_to "Back to courses", courses_path %>
  <%= button_to "Destroy this course", @course, method: :delete %>
  <%= button_to 'Ajouter cours' , cart_add_course_path(@course.id), method: "post" %>
</div>